name: Keycloak Integration CI

on: 
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_JDK_VERSION: 17
  DEFAULT_JDK_DIST: temurin

jobs:

  tests-extension:
    name: Extension
    runs-on: ubuntu-latest
    strategy:
      matrix:
        retries: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.DEFAULT_JDK_DIST }}
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/maven-settings.xml ~/.m2/

      - name: Cache Maven repo
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Get Keycloak
        run: .github/scripts/prepare-local-server.sh

      - name: Start Keycloak
        run: .github/scripts/start-local-server.sh extension

      - name: Run unit tests (just extend-account-console)
        run: mvn clean install -f extension/extend-account-console/pom.xml -Dnightly -Dwebdriver.chrome.driver=${CHROMEWEBDRIVER}/chromedriver -Dextension -B

